apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: basic-install
spec:
  profile: default
  meshConfig:
    enableTracing: false
    defaultConfig:
      tracing:
        sampling: 0
  components:
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s:
        env:
        - name: ISTIO_METAJSON_ANNOTATIONS
          value: |
            {"sidecar.istio.io/statsInclusionPrefixes": "cluster_manager,listener_manager"}
        nodeSelector:
          test.role: router
        replicaCount: 1
        resources:
          limits:
            cpu: "256"
            memory: 256Gi
          requests:
            cpu: "16"
            memory: 2Gi
    cni:
      namespace: kube-system
      enabled: true
    pilot:
      k8s:
        replicaCount: 1
  values:
    cni:
      cniBinDir: /var/lib/cni/bin
      cniConfDir: /etc/cni/multus/net.d
      cniConfFileName: istio-cni.conf
      chained: false
      excludeNamespaces:
       - istio-system
       - kube-system
      logLevel: info
    gateways:
      istio-ingressgateway:
        tolerations:
        - key: "gateway"
          effect: "NoExecute" 
        autoscaleEnabled: false
    global:
      proxy:
        autoInject: disabled
      # Prevents reaching DockerHub thresholds
      imagePullPolicy: IfNotPresent
    pilot:
      autoscaleEnabled: false
      traceSampling: 0
    sidecarInjectorWebhook:
      injectedAnnotations:
        k8s.v1.cni.cncf.io/networks: istio-cni
    telemetry:
      enabled: false

